"""Generate design/tokens.css — the design system the mockups share.

The Bootstrap Icons woff2 is embedded as a data URI so every mockup renders
standalone in the Claude Design pane, which has no access to the app's
/static/vendor tree. The app itself keeps using the vendored font file; this
embedding exists only so the designs show the *real* icons rather than
placeholder glyphs.
"""
import base64
import json
import pathlib

HERE = pathlib.Path(__file__).parent
ROOT = HERE.parent

font = (ROOT / 'static/vendor/bootstrap-icons/fonts/bootstrap-icons.woff2').read_bytes()
b64 = base64.b64encode(font).decode('ascii')

ICONS = json.loads((HERE / 'icons.json').read_text(encoding='utf-8'))
icon_rules = '\n'.join(
    f'.bi-{name}::before {{ content: "\\{code}"; }}' for name, code in ICONS.items())

CSS = f"""/* TrackTrack design system — generated by design/build_tokens.py, do not hand-edit.

   Direction: B on desktop, C on phone.

   Desktop keeps the frosted glass and the density — there is room for it, and no
   glare. Below 768px the surfaces go solid, contrast goes up, the blur goes away
   and navigation moves to the bottom in thumb reach. Same app, two honest
   layouts, because a phone in a market doorway is a different machine from a
   laptop on a desk.
*/

/* --- the real icons, embedded so mockups stand alone --------------------- */
@font-face {{
  font-family: "bootstrap-icons";
  src: url("data:font/woff2;base64,{b64}") format("woff2");
  font-display: block;
}}
.bi::before, [class^="bi-"]::before, [class*=" bi-"]::before {{
  display: inline-block;
  font-family: "bootstrap-icons" !important;
  font-style: normal; font-weight: normal !important;
  font-variant: normal; text-transform: none; line-height: 1;
  vertical-align: -0.125em;
  -webkit-font-smoothing: antialiased;
}}
{icon_rules}

/* --- scales -------------------------------------------------------------- */
.tt {{
  --t-xs: 0.75rem; --t-sm: 0.8125rem; --t-md: 0.9375rem;
  --t-lg: 1.0625rem; --t-xl: 1.5rem; --t-2xl: 1.875rem; --t-3xl: 2.5rem;
  --s1: 4px; --s2: 8px; --s3: 12px; --s4: 16px; --s5: 24px; --s6: 32px;
  --radius: 14px; --radius-sm: 9px;
  --tap: 48px;              /* nothing touchable is smaller than this */
  --rail-w: 60px;
}}

/* --- dark: the identity, with the accent lifted -------------------------- */
.tt[data-theme="dark"] {{
  --page: #080f1c;
  --surface: rgba(23, 34, 54, 0.74);
  --surface-solid: #16213a;
  --rail: rgba(11, 18, 32, 0.94);
  --bar: rgba(15, 23, 42, 0.70);
  --line: rgba(148, 163, 184, 0.15);
  --line-solid: #334155;
  --ink: #f1f5f9;
  --ink-soft: #93a3b8;
  --accent: #60a5fa;        /* was #3b82f6 — 3.98:1, under AA on this card */
  --on-accent: #06142b;
  --good: #34d399; --warn: #fbbf24; --bad: #f87171;
  --good-bg: rgba(52,211,153,0.16);
  --warn-bg: rgba(251,191,36,0.16);
  --bad-bg: rgba(248,113,113,0.16);
  --blur: blur(12px);
  --shadow: 0 10px 34px rgba(0,0,0,0.40);
}}

/* --- light: frosted white, same family ----------------------------------- */
.tt[data-theme="light"] {{
  --page: #e9eef5;
  --surface: rgba(255, 255, 255, 0.82);
  --surface-solid: #ffffff;
  --rail: rgba(255, 255, 255, 0.94);
  --bar: rgba(255, 255, 255, 0.72);
  --line: rgba(15, 23, 42, 0.10);
  --line-solid: #cbd5e1;
  --ink: #0f172a;
  --ink-soft: #52627a;      /* 5.9:1 — #64748b fails at 4.2 */
  --accent: #2563eb;        /* 4.9:1 — #3b82f6 fails at 3.3 on white */
  --on-accent: #ffffff;
  --good: #047857; --warn: #854d0e; --bad: #b91c1c;
  --good-bg: #d1fae5; --warn-bg: #fef3c7; --bad-bg: #fee2e2;
  --blur: blur(12px);
  --shadow: 0 10px 30px rgba(15,23,42,0.10);
}}

/* --- phone: solid surfaces, no blur, more contrast ----------------------- */
@media (max-width: 767.98px) {{
  .tt[data-theme="dark"] {{
    --surface: #16213a; --rail: #0b1220; --bar: #0b1220;
    --line: #334155; --ink-soft: #b6c2d4; --blur: none;
    --shadow: none;
  }}
  .tt[data-theme="light"] {{
    --page: #ffffff; --surface: #f1f5f9; --rail: #ffffff; --bar: #ffffff;
    --line: #cbd5e1; --ink-soft: #475569; --accent: #1d4ed8; --blur: none;
    --shadow: none;
  }}
}}

/* Mockups only. A phone frame sitting inside a wide page never triggers the
   media query above, because that keys off the viewport rather than the
   element. `.is-phone` applies the same overrides so a phone mockup can be
   shown honestly next to a desktop one. The app itself uses the media query
   and never this class. */
.tt.is-phone[data-theme="dark"] {{
  --surface: #16213a; --rail: #0b1220; --bar: #0b1220;
  --line: #334155; --ink-soft: #b6c2d4; --blur: none; --shadow: none;
}}
.tt.is-phone[data-theme="light"] {{
  --page: #ffffff; --surface: #f1f5f9; --rail: #ffffff; --bar: #ffffff;
  --line: #cbd5e1; --ink-soft: #475569; --accent: #1d4ed8;
  --blur: none; --shadow: none;
}}

/* --- base ---------------------------------------------------------------- */
.tt {{
  font: 400 var(--t-md)/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
  background: var(--page); color: var(--ink);
  border: 1px solid var(--line); border-radius: var(--radius);
  overflow: hidden;
}}
.tt *, .tt *::before, .tt *::after {{ box-sizing: border-box; }}
.tt .num {{ font-variant-numeric: tabular-nums; }}

/* --- surfaces ------------------------------------------------------------ */
.tt .card {{
  background: var(--surface); backdrop-filter: var(--blur);
  border: 1px solid var(--line); border-radius: var(--radius);
  box-shadow: var(--shadow); padding: var(--s4) var(--s5) var(--s5);
}}
.tt .card > h2 {{
  font-size: var(--t-sm); font-weight: 600; margin: 0 0 var(--s4);
  text-transform: uppercase; letter-spacing: 0.07em; color: var(--ink-soft);
  display: flex; align-items: center; gap: var(--s2);
}}
.tt .card > h2 .more {{
  margin-left: auto; text-transform: none; letter-spacing: 0;
  color: var(--accent); font-size: var(--t-xs); text-decoration: none;
}}

/* --- buttons ------------------------------------------------------------- */
.tt .btn {{
  display: inline-flex; align-items: center; justify-content: center;
  gap: var(--s2); min-height: 36px; padding: 0 var(--s4);
  border-radius: var(--radius-sm); border: 1px solid transparent;
  font: 600 var(--t-sm)/1 inherit; cursor: pointer; white-space: nowrap;
}}
.tt .btn-primary {{ background: var(--accent); color: var(--on-accent); }}
.tt .btn-ghost {{ background: transparent; color: var(--ink-soft);
  border-color: var(--line); }}
.tt .btn-ghost:hover {{ color: var(--ink); }}
.tt .btn-icon {{ width: 36px; padding: 0; }}
.tt .btn-lg {{ min-height: var(--tap); font-size: var(--t-md);
  width: 100%; border-radius: var(--radius); }}

/* --- badges -------------------------------------------------------------- */
.tt .badge {{
  display: inline-flex; align-items: center; gap: 4px;
  font-size: var(--t-xs); font-weight: 700; padding: 3px 9px;
  border-radius: 20px; white-space: nowrap;
}}
.tt .badge-good {{ background: var(--good-bg); color: var(--good); }}
.tt .badge-warn {{ background: var(--warn-bg); color: var(--warn); }}
.tt .badge-bad  {{ background: var(--bad-bg);  color: var(--bad); }}
.tt .badge-mute {{ background: color-mix(in srgb, var(--ink) 10%, transparent);
  color: var(--ink-soft); }}

/* --- tables -------------------------------------------------------------- */
.tt table {{ width: 100%; border-collapse: collapse; font-size: var(--t-sm); }}
.tt thead th {{
  text-align: left; font-size: var(--t-xs); font-weight: 700;
  text-transform: uppercase; letter-spacing: 0.06em; color: var(--ink-soft);
  padding: var(--s2) var(--s3); border-bottom: 1px solid var(--line);
}}
.tt tbody td {{ padding: var(--s3); border-bottom: 1px solid var(--line); }}
.tt tbody tr:last-child td {{ border-bottom: 0; }}
.tt tbody tr:hover td {{ background: color-mix(in srgb, var(--accent) 7%, transparent); }}
.tt td.right, .tt th.right {{ text-align: right; }}

/* --- forms --------------------------------------------------------------- */
.tt .field {{ margin-bottom: var(--s4); }}
.tt .field label {{
  display: block; font-size: var(--t-xs); font-weight: 600;
  text-transform: uppercase; letter-spacing: 0.06em;
  color: var(--ink-soft); margin-bottom: var(--s2);
}}
.tt .field input, .tt .field select {{
  width: 100%; min-height: 40px; padding: 0 var(--s3);
  background: color-mix(in srgb, var(--ink) 6%, transparent);
  border: 1px solid var(--line); border-radius: var(--radius-sm);
  color: var(--ink); font: inherit; font-size: var(--t-sm);
}}
.tt .field input::placeholder {{ color: var(--ink-soft); }}
.tt .field input:focus, .tt .field select:focus {{
  outline: 2px solid var(--accent); outline-offset: 1px; border-color: transparent;
}}
.tt .hint {{ font-size: var(--t-xs); color: var(--ink-soft); margin-top: var(--s1); }}

/* --- empty state --------------------------------------------------------- */
.tt .empty {{ text-align: center; padding: var(--s6) var(--s4); }}
.tt .empty .mark {{
  width: 44px; height: 44px; border-radius: 50%; display: grid;
  place-items: center; margin: 0 auto var(--s3); font-size: 20px;
  background: var(--good-bg); color: var(--good);
}}
.tt .empty b {{ display: block; font-size: var(--t-md); margin-bottom: var(--s1); }}
.tt .empty p {{ margin: 0 0 var(--s4); color: var(--ink-soft); font-size: var(--t-sm); }}

/* --- stat strip (desktop) ------------------------------------------------ */
.tt .strip {{
  display: grid; grid-template-columns: repeat(4, 1fr);
  background: var(--surface); backdrop-filter: var(--blur);
  border: 1px solid var(--line); border-radius: var(--radius);
  box-shadow: var(--shadow);
}}
.tt .strip .cell {{ padding: var(--s4) var(--s5); border-right: 1px solid var(--line); }}
.tt .strip .cell:last-child {{ border-right: 0; }}
.tt .strip .lab {{
  font-size: var(--t-xs); text-transform: uppercase; letter-spacing: 0.08em;
  color: var(--ink-soft);
}}
.tt .strip .val {{
  font-size: var(--t-2xl); font-weight: 700; line-height: 1.15;
  letter-spacing: -0.02em; margin-top: 2px; font-variant-numeric: tabular-nums;
}}
.tt .strip .val.accent {{ color: var(--accent); }}
.tt .strip .d {{ font-size: var(--t-xs); margin-top: 2px; color: var(--ink-soft); }}
.tt .strip .d.up {{ color: var(--good); }}

/* --- hero number (phone) ------------------------------------------------- */
.tt .hero {{
  background: var(--accent); color: var(--on-accent);
  border-radius: var(--radius); padding: var(--s5);
}}
.tt .hero .lab {{ font-size: var(--t-sm); font-weight: 600; opacity: 0.92; }}
.tt .hero .val {{
  font-size: var(--t-3xl); font-weight: 800; line-height: 1.05;
  letter-spacing: -0.03em; margin-top: var(--s1); font-variant-numeric: tabular-nums;
}}
.tt .hero .d {{ font-size: var(--t-sm); opacity: 0.92; margin-top: var(--s1); }}
"""

(HERE / 'tokens.css').write_text(CSS, encoding='utf-8')
print(f'tokens.css written — {len(CSS):,} bytes ({len(ICONS)} icons embedded)')
