"""add_registration_fields

Revision ID: 485dd2872397
Revises: b56a6785013e
Create Date: 2026-07-10 14:51:07.693728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485dd2872397'
down_revision = 'b56a6785013e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('uq_business_email', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('uq_business_email', ['business_id', 'email'])
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('logo_path')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
