"""enforce_not_null_variants

Revision ID: b56a6785013e
Revises: 036c2bcb7078
Create Date: 2026-07-10 08:35:35.545037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56a6785013e'
down_revision = '036c2bcb7078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('item_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('base_uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('purchase_uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('units_per_purchase_uom',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('units_per_purchase_uom',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('purchase_uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('base_uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('item_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
